       IDENTIFICATION DIVISION.
       PROGRAM-ID. LEARN-COBOL.

       DATE-WRITTEN "04/03/2025".
       DATE-MODIFIED "04/03/2025".
       DATE-COMPILED "04/03/2025".
       INSTALLATION "Pepe INC SAS".
       SECURITY "Open Source".
       REMARKS "Esta es la primera prueba".

       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
           SPECIAL-NAMES.
               DECIMAL-POINT IS COMMA.
               SYMBOLIC CHARACTERS ESPACIO IS 33.

       DATA DIVISION.
       FILE SECTION.
       WORKING-STORAGE SECTION.
       PROCEDURE DIVISION.
       MAIN-PROCEDURE.
           DISPLAY "HOLA" ESPACIO "COBOL".
            STOP RUN.
       END PROGRAM LEARN-COBOL.
